// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// clear
export const CLEAR_ALL = "CLEAR_ALL";

// Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Company
export const ADD_COMPANY = "ADD_COMPANY";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const GET_COMPANY_NAME = "GET_COMPANY_NAME";
export const GET_COMPANY_NAME_SUCCESS = "GET_COMPANY_NAME_SUCCESS";
export const LOOKING_FOR_TEXT = "LOOKING_FOR_TEXT";
export const LOOKING_FOR_TEXT_SUCCESS = "LOOKING_FOR_TEXT_SUCCESS";
export const COMPANY_REQUESTS = "COMPANY_REQUESTS";
export const COMPANY_REQUESTS_SUCCESS = "COMPANY_REQUESTS_SUCCESS";
export const FETCH_ADD_LOCATION = "FETCH_ADD_LOCATION";
export const FETCH_ADD_LOCATION_SUCCESS = "FETCH_ADD_LOCATION_SUCCESS";
export const ADD_NEW_LOCATION = "ADD_NEW_LOCATION";
export const ADD_NEW_LOCATION_SUCCESS = "ADD_NEW_LOCATION_SUCCESS";
export const FETCH_EDITABLE_NAMES = "FETCH_EDITABLE_NAMES";
export const FETCH_EDITABLE_NAMES_SUCCESS = "FETCH_EDITABLE_NAMES_SUCCESS";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const FETCH_LABOUR_SUPPLY = "FETCH_LABOUR_SUPPLY";
export const FETCH_LABOUR_SUPPLY_SUCCESS = "FETCH_LABOUR_SUPPLY_SUCCESS";
export const FETCH_LABOUR_DEMAND = "FETCH_LABOUR_DEMAND";
export const FETCH_LABOUR_DEMAND_SUCCESS = "FETCH_LABOUR_DEMAND_SUCCESS";
export const FETCH_AVERAGE_WAGE = "FETCH_AVERAGE_WAGE";
export const FETCH_AVERAGE_WAGE_SUCCESS = "FETCH_AVERAGE_WAGE_SUCCESS";
export const FETCH_AVERAGE_WORK_TIME = "FETCH_AVERAGE_WORK_TIME";
export const FETCH_AVERAGE_WORK_TIME_SUCCESS =
  "FETCH_AVERAGE_WORK_TIME_SUCCESS";
export const UPDATE_CONTACT_DETAILS = "UPDATE_CONTACT_DETAILS";
export const UPDATE_CONTACT_DETAILS_SUCCESS = "UPDATE_CONTACT_DETAILS_SUCCESS";
// labour
export const ADD_LABOUR_REQUIREMENT = "ADD_LABOUR_REQUIREMENT";
export const ADD_LABOUR_REQUIREMENT_SUCCESS = "ADD_LABOUR_REQUIREMENT_SUCCESS";
export const FETCH_ACTIVE_LABOURS = "FETCH_ACTIVE_LABOURS";
export const FETCH_ACTIVE_LABOURS_SUCCESS = "FETCH_ACTIVE_LABOURS_SUCCESS";
export const FETCH_LABOUR_SELECTION = "FETCH_LABOUR_SELECTION";
export const FETCH_LABOUR_SELECTION_SUCCESS = "FETCH_LABOUR_SELECTION_SUCCESS";

export const ADD_LABOUR = "ADD_LABOUR";
export const COMPANY_SELECTION = "COMPANY_SELECTION";
export const ADD_LABOUR_SUCCESS = "ADD_LABOUR_SUCCESS";
export const COMPANY_SELECTION_SUCCESS = "COMPANY_SELECTION_SUCCESS";
export const FETCH_ACTIVE_JOB_STATS = "FETCH_ACTIVE_JOB_STATS";
export const FETCH_ACTIVE_JOB_STATS_SUCCESS = "FETCH_ACTIVE_JOB_STATS_SUCCESS";
export const LABOUR_LOOKING_FOR = "LABOUR_LOOKING_FOR";
export const LABOUR_LOOKING_FOR_SUCCESS = "LABOUR_LOOKING_FOR_SUCCESS";
export const FETCH_LABOUR_NAME = "FETCH_LABOUR_NAME";
export const FETCH_LABOUR_NAME_SUCCESS = "FETCH_LABOUR_NAME_SUCCESS";
export const FETCH_JOB_AVAILABLE_STATS = "FETCH_JOB_AVAILABLE_STATS";
export const FETCH_JOB_AVAILABLE_STATS_SUCCESS =
  "FETCH_JOB_AVAILABLE_STATS_SUCCESS";
export const DELETE_LABOUR = "DELETE_LABOUR";
export const DELETE_LABOUR_SUCCESS = "DELETE_LABOUR_SUCCESS";
export const FETCH_EDITABLE_LABOUR = "FETCH_EDITABLE_LABOUR";
export const FETCH_EDITABLE_LABOUR_SUCCESS = "FETCH_EDITABLE_LABOUR_SUCCESS";
export const UPDATE_LABOUR_PHONE_CONTACT = "UPDATE_LABOUR_PHONE_CONTACT";
export const UPDATE_LABOUR_PHONE_CONTACT_SUCCESS =
  "UPDATE_LABOUR_PHONE_CONTACT_SUCCESS";

// coordinator

export const REGISTER_COORDINATOR = "REGISTER_COORDINATOR";
export const ADD_LABOUR_BY_COORDINATOR = "ADD_LABOUR_BY_COORDINATOR";
export const ADD_LABOUR_BY_COORDINATOR_SUCCESS =
  "ADD_LABOUR_BY_COORDINATOR_SUCCESS";
export const COORDINATOR_COMPANY_SELECTION = "COORDINATOR_COMPANY_SELECTION";
export const COORDINATOR_COMPANY_SELECTION_SUCCESS =
  "COORDINATOR_COMPANY_SELECTION_SUCCESS";
export const COORDINATOR_LABOUR_LOOKING_FOR = "COORDINATOR_LABOUR_LOOKING_FOR";
export const COORDINATOR_LABOUR_LOOKING_FOR_SUCCESS =
  "COORDINATOR_LABOUR_LOOKING_FOR_SUCCESS";
export const COORDINATOR_LABOUR_NAME = "COORDINATOR_LABOUR_NAME";
export const COORDINATOR_LABOUR_NAME_SUCCESS =
  "COORDINATOR_LABOUR_NAME_SUCCESS";
export const COORDINATOR_JOB_AVAILABLE_STATS =
  "COORDINATOR_JOB_AVAILABLE_STATS";
export const COORDINATOR_JOB_AVAILABLE_STATS_SUCCESS =
  "COORDINATOR_JOB_AVAILABLE_STATS_SUCCESS";
export const DELETE_COORDINATOR = "DELETE_COORDINATOR";
export const COORDINATOR_EDIT_DETAILS = "COORDINATOR_EDIT_DETAILS";
export const COORDINATOR_EDIT_DETAILS_SUCCESS =
  "COORDINATOR_EDIT_DETAILS_SUCCESS";
export const COORDINATOR_UPDATE_DETAILS = "COORDINATOR_UPDATE_DETAILS";
export const COORDINATOR_UPDATE_DETAILS_SUCCESS =
  "COORDINATOR_UPDATE_DETAILS_SUCCESS";
